In [15]:
# organize imports
import cv2
import imutils
import numpy as np

# global variables
bg = None

#-------------------------------------------------------------------------------
# Function - To find the running average over the background
#-------------------------------------------------------------------------------
def run_avg(image, aWeight):
    global bg
    # initialize the background
    if bg is None:
        bg = image.copy().astype("float")
        return

    # compute weighted average, accumulate it and update the background
    cv2.accumulateWeighted(image, bg, aWeight)

#-------------------------------------------------------------------------------
# Function - To segment the region of hand in the image
#-------------------------------------------------------------------------------
def segment(image, threshold=17):
    global bg
    # find the absolute difference between background and current frame
    diff = cv2.absdiff(bg.astype("uint8"), image)

    # threshold the diff image so that we get the foreground
    thresholded = cv2.threshold(diff,
                                threshold,
                                255,
                                cv2.THRESH_BINARY)[1]

    # get the contours in the thresholded image
    (_, cnts, _) = cv2.findContours(thresholded.copy(),
                                    cv2.RETR_EXTERNAL,
                                    cv2.CHAIN_APPROX_SIMPLE)

    # return None, if no contours detected
    if len(cnts) == 0:
        return
    else:
        # based on contour area, get the maximum contour which is the hand
        segmented = max(cnts, key=cv2.contourArea)
        return (thresholded, segmented)

#-------------------------------------------------------------------------------
# Main function
#-------------------------------------------------------------------------------
if __name__ == "__main__":
    # initialize weight for running average
    aWeight = 0.5

    # get the reference to the webcam
    camera = cv2.VideoCapture(0)

    # region of interest (ROI) coordinates
    top, right, bottom, left = 10, 350, 225, 590

    # initialize num of frames
    num_frames = 0

    # keep looping, until interrupted
    while(True):
        # get the current frame
        (grabbed, frame) = camera.read()

        # resize the frame
        frame = imutils.resize(frame, width=700)

        # flip the frame so that it is not the mirror view
        frame = cv2.flip(frame, 1)

        # clone the frame
        clone = frame.copy()

        # get the height and width of the frame
        (height, width) = frame.shape[:2]

        # get the ROI
        roi = frame[top:bottom, right:left]

        # convert the roi to grayscale and blur it
        gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
        gray = cv2.GaussianBlur(gray, (7, 7), 0)

        # to get the background, keep looking till a threshold is reached
        # so that our running average model gets calibrated
        if num_frames < 30:
            run_avg(gray, aWeight)
        else:
            # segment the hand region
            hand = segment(gray)

            # check whether hand region is segmented
            if hand is not None:
                # if yes, unpack the thresholded image and
                # segmented region
                (thresholded, segmented) = hand
                print(segmented)
                # draw the segmented region and display the frame
                cv2.drawContours(clone, [segmented + (right, top)], -1, (0, 0, 255))
                cv2.imwrite(str(num_frames)+'.png',thresholded)
                cv2.imshow("Thesholded", thresholded)

        # draw the segmented hand
        cv2.rectangle(clone, (left, top), (right, bottom), (0,255,0), 2)

        # increment the number of frames
        num_frames += 1

        # display the frame with segmented hand
        
        cv2.imshow("Video Feed", clone)

        # observe the keypress by the user
        keypress = cv2.waitKey(1) & 0xFF

        # if the user pressed "q", then stop looping
        if keypress == ord("q"):
            break
            

# free up memory
camera.release()
cv2.destroyAllWindows()

[[[168 136]]

 [[167 137]]

 [[168 138]]

 [[170 138]]

 [[170 137]]

 [[169 137]]]
[[[120 144]]]
[[[75 90]]]
[[[191  81]]

 [[190  82]]

 [[191  82]]]
[[[124 152]]

 [[125 153]]

 [[125 152]]]
[[[104 152]]

 [[106 152]]]
[[[ 72 210]]

 [[ 71 211]]

 [[ 70 211]]

 [[ 69 212]]

 [[ 68 212]]

 [[ 67 213]]

 [[ 67 214]]

 [[ 84 214]]

 [[ 84 213]]

 [[ 83 212]]

 [[ 82 212]]

 [[ 81 211]]

 [[ 80 211]]

 [[ 79 210]]]
[[[ 73 198]]

 [[ 72 199]]

 [[ 70 199]]

 [[ 65 204]]

 [[ 64 203]]

 [[ 62 203]]

 [[ 61 202]]

 [[ 54 202]]

 [[ 53 203]]

 [[ 52 203]]

 [[ 51 204]]

 [[ 50 204]]

 [[ 49 205]]

 [[ 49 206]]

 [[ 48 207]]

 [[ 48 208]]

 [[ 47 209]]

 [[ 47 210]]

 [[ 46 211]]

 [[ 46 214]]

 [[102 214]]

 [[102 213]]

 [[101 212]]

 [[101 211]]

 [[100 211]]

 [[ 99 210]]

 [[ 95 210]]

 [[ 94 209]]

 [[ 89 209]]

 [[ 86 206]]

 [[ 86 205]]

 [[ 85 204]]

 [[ 85 203]]

 [[ 82 200]]

 [[ 81 200]]

 [[ 80 199]]

 [[ 78 199]]

 [[ 77 198]]]
[[[ 72 185]]

 [[ 71 186]]

 [[ 70 186]]

 [[ 68 1

[[[156  97]]

 [[155  98]]

 [[154  98]]

 [[153  99]]

 [[151  99]]

 [[150 100]]

 [[149 100]]

 [[148 101]]

 [[147 101]]

 [[144 104]]

 [[143 104]]

 [[142 105]]

 [[141 105]]

 [[140 106]]

 [[138 106]]

 [[137 105]]

 [[135 105]]

 [[134 106]]

 [[132 106]]

 [[131 107]]

 [[129 107]]

 [[128 108]]

 [[126 108]]

 [[125 109]]

 [[123 109]]

 [[118 114]]

 [[117 114]]

 [[112 119]]

 [[112 120]]

 [[109 123]]

 [[109 124]]

 [[107 126]]

 [[107 127]]

 [[105 129]]

 [[105 130]]

 [[103 132]]

 [[103 133]]

 [[102 134]]

 [[102 135]]

 [[101 136]]

 [[101 137]]

 [[100 138]]

 [[100 140]]

 [[ 98 142]]

 [[ 98 143]]

 [[ 97 144]]

 [[ 97 146]]

 [[ 96 147]]

 [[ 96 148]]

 [[ 95 149]]

 [[ 95 150]]

 [[ 94 151]]

 [[ 94 152]]

 [[ 93 153]]

 [[ 93 154]]

 [[ 92 155]]

 [[ 92 157]]

 [[ 91 158]]

 [[ 91 159]]

 [[ 90 160]]

 [[ 90 161]]

 [[ 89 162]]

 [[ 89 163]]

 [[ 88 164]]

 [[ 88 166]]

 [[ 87 167]]

 [[ 87 168]]

 [[ 86 169]]

 [[ 86 170]]

 [[ 85 171]]

 [[ 85 172]]

 [[ 84

[[[194  47]]

 [[193  48]]

 [[190  48]]

 [[189  49]]

 [[186  49]]

 [[185  50]]

 [[183  50]]

 [[182  51]]

 [[181  51]]

 [[180  52]]

 [[179  52]]

 [[177  54]]

 [[167  54]]

 [[166  55]]

 [[161  55]]

 [[160  56]]

 [[158  56]]

 [[157  57]]

 [[156  57]]

 [[155  58]]

 [[154  58]]

 [[153  59]]

 [[152  59]]

 [[150  61]]

 [[149  61]]

 [[144  66]]

 [[143  66]]

 [[135  74]]

 [[135  75]]

 [[133  77]]

 [[133  78]]

 [[131  80]]

 [[131  81]]

 [[130  82]]

 [[130  83]]

 [[129  84]]

 [[129  85]]

 [[127  87]]

 [[127  88]]

 [[126  89]]

 [[126  90]]

 [[124  92]]

 [[124  93]]

 [[123  94]]

 [[123  95]]

 [[122  96]]

 [[122  97]]

 [[119 100]]

 [[119 101]]

 [[118 102]]

 [[118 103]]

 [[117 104]]

 [[117 105]]

 [[116 106]]

 [[116 107]]

 [[115 108]]

 [[115 109]]

 [[114 110]]

 [[114 112]]

 [[113 113]]

 [[113 115]]

 [[112 116]]

 [[112 118]]

 [[111 119]]

 [[111 121]]

 [[110 122]]

 [[110 123]]

 [[109 124]]

 [[109 126]]

 [[108 127]]

 [[108 129]]

 [[107

[[[204  34]]

 [[203  35]]

 [[202  35]]

 [[201  36]]

 [[199  36]]

 [[197  38]]

 [[196  38]]

 [[195  39]]

 [[194  39]]

 [[193  40]]

 [[191  40]]

 [[190  41]]

 [[189  41]]

 [[188  40]]

 [[184  40]]

 [[183  39]]

 [[182  40]]

 [[176  40]]

 [[175  41]]

 [[173  41]]

 [[172  42]]

 [[171  42]]

 [[170  43]]

 [[169  43]]

 [[168  44]]

 [[167  44]]

 [[166  45]]

 [[165  45]]

 [[163  47]]

 [[162  47]]

 [[157  52]]

 [[156  52]]

 [[152  56]]

 [[151  56]]

 [[149  58]]

 [[149  59]]

 [[145  63]]

 [[141  63]]

 [[140  62]]

 [[139  63]]

 [[137  63]]

 [[136  64]]

 [[136  65]]

 [[135  66]]

 [[135  67]]

 [[134  68]]

 [[134  69]]

 [[133  70]]

 [[133  73]]

 [[132  74]]

 [[132  77]]

 [[131  78]]

 [[131  79]]

 [[130  80]]

 [[130  82]]

 [[129  83]]

 [[129  84]]

 [[127  86]]

 [[127  87]]

 [[126  88]]

 [[126  89]]

 [[125  90]]

 [[125  91]]

 [[124  92]]

 [[124  93]]

 [[122  95]]

 [[122  96]]

 [[121  97]]

 [[121  98]]

 [[120  99]]

 [[120 100]]

 [[119

[[[221  34]]

 [[220  35]]

 [[218  35]]

 [[217  36]]

 [[216  36]]

 [[213  39]]

 [[212  39]]

 [[210  41]]

 [[209  41]]

 [[206  44]]

 [[205  44]]

 [[204  43]]

 [[204  40]]

 [[203  39]]

 [[203  38]]

 [[202  37]]

 [[201  37]]

 [[200  36]]

 [[195  36]]

 [[194  37]]

 [[193  37]]

 [[192  38]]

 [[191  38]]

 [[190  39]]

 [[189  39]]

 [[188  40]]

 [[187  40]]

 [[185  42]]

 [[184  42]]

 [[182  44]]

 [[181  44]]

 [[180  45]]

 [[180  46]]

 [[179  47]]

 [[178  47]]

 [[173  52]]

 [[172  52]]

 [[165  59]]

 [[164  59]]

 [[160  55]]

 [[159  55]]

 [[158  54]]

 [[156  54]]

 [[153  57]]

 [[153  59]]

 [[152  60]]

 [[152  62]]

 [[151  63]]

 [[151  64]]

 [[150  65]]

 [[150  67]]

 [[149  68]]

 [[149  69]]

 [[148  70]]

 [[148  71]]

 [[146  73]]

 [[146  74]]

 [[145  75]]

 [[145  76]]

 [[143  78]]

 [[143  79]]

 [[142  80]]

 [[142  81]]

 [[139  84]]

 [[139  85]]

 [[138  86]]

 [[138  87]]

 [[136  89]]

 [[136  90]]

 [[132  94]]

 [[132  95]]

 [[131

[[[208  29]]

 [[207  30]]

 [[204  30]]

 [[203  31]]

 [[202  31]]

 [[199  34]]

 [[198  34]]

 [[196  36]]

 [[193  36]]

 [[188  31]]

 [[187  31]]

 [[186  30]]

 [[180  30]]

 [[179  31]]

 [[178  31]]

 [[177  32]]

 [[176  32]]

 [[175  33]]

 [[174  33]]

 [[172  35]]

 [[171  35]]

 [[169  37]]

 [[168  37]]

 [[159  46]]

 [[158  46]]

 [[155  49]]

 [[154  49]]

 [[153  50]]

 [[153  51]]

 [[150  54]]

 [[149  54]]

 [[148  55]]

 [[147  55]]

 [[145  53]]

 [[145  51]]

 [[144  50]]

 [[144  49]]

 [[143  48]]

 [[143  47]]

 [[142  46]]

 [[141  46]]

 [[140  45]]

 [[136  45]]

 [[134  47]]

 [[134  49]]

 [[133  50]]

 [[133  53]]

 [[132  54]]

 [[132  55]]

 [[131  56]]

 [[131  58]]

 [[130  59]]

 [[130  60]]

 [[129  61]]

 [[129  62]]

 [[128  63]]

 [[128  64]]

 [[127  65]]

 [[127  67]]

 [[126  68]]

 [[126  69]]

 [[125  70]]

 [[125  71]]

 [[123  73]]

 [[123  74]]

 [[122  75]]

 [[122  76]]

 [[121  77]]

 [[121  78]]

 [[120  79]]

 [[120  80]]

 [[119

[[[163  37]]

 [[162  38]]

 [[160  38]]

 [[159  39]]

 [[157  39]]

 [[156  40]]

 [[155  40]]

 [[152  43]]

 [[151  43]]

 [[145  49]]

 [[144  49]]

 [[139  54]]

 [[138  54]]

 [[135  57]]

 [[135  58]]

 [[133  60]]

 [[132  60]]

 [[131  61]]

 [[131  62]]

 [[130  63]]

 [[129  63]]

 [[126  66]]

 [[125  66]]

 [[124  65]]

 [[124  64]]

 [[123  63]]

 [[123  58]]

 [[122  57]]

 [[122  54]]

 [[121  53]]

 [[121  52]]

 [[120  52]]

 [[119  51]]

 [[116  51]]

 [[115  52]]

 [[113  52]]

 [[112  53]]

 [[112  54]]

 [[111  55]]

 [[111  56]]

 [[110  57]]

 [[110  58]]

 [[109  59]]

 [[109  61]]

 [[108  62]]

 [[108  63]]

 [[107  64]]

 [[107  65]]

 [[105  67]]

 [[105  69]]

 [[104  70]]

 [[104  71]]

 [[103  72]]

 [[103  73]]

 [[102  74]]

 [[102  75]]

 [[100  77]]

 [[100  78]]

 [[ 99  79]]

 [[ 99  80]]

 [[ 98  81]]

 [[ 98  82]]

 [[ 96  84]]

 [[ 96  85]]

 [[ 93  88]]

 [[ 93  89]]

 [[ 92  90]]

 [[ 92  91]]

 [[ 91  92]]

 [[ 91  93]]

 [[ 90  94]]

 [[ 90

[[[164  40]]

 [[163  41]]

 [[162  41]]

 [[161  42]]

 [[160  42]]

 [[159  43]]

 [[158  43]]

 [[156  45]]

 [[155  45]]

 [[152  48]]

 [[151  48]]

 [[143  56]]

 [[142  56]]

 [[120  78]]

 [[119  78]]

 [[115  82]]

 [[114  82]]

 [[111  85]]

 [[108  85]]

 [[107  84]]

 [[107  78]]

 [[108  77]]

 [[108  69]]

 [[107  68]]

 [[107  67]]

 [[106  66]]

 [[106  62]]

 [[105  61]]

 [[105  60]]

 [[104  59]]

 [[104  58]]

 [[103  57]]

 [[103  56]]

 [[100  53]]

 [[ 99  53]]

 [[ 98  52]]

 [[ 97  53]]

 [[ 96  53]]

 [[ 95  54]]

 [[ 95  55]]

 [[ 94  56]]

 [[ 94  62]]

 [[ 93  63]]

 [[ 93  66]]

 [[ 92  67]]

 [[ 92  70]]

 [[ 91  71]]

 [[ 91  73]]

 [[ 90  74]]

 [[ 90  78]]

 [[ 89  79]]

 [[ 89  81]]

 [[ 88  82]]

 [[ 88  84]]

 [[ 87  85]]

 [[ 87  86]]

 [[ 86  87]]

 [[ 86  88]]

 [[ 85  89]]

 [[ 85  90]]

 [[ 84  91]]

 [[ 84  92]]

 [[ 83  93]]

 [[ 83  95]]

 [[ 82  96]]

 [[ 82  98]]

 [[ 81  99]]

 [[ 81 111]]

 [[ 82 112]]

 [[ 82 132]]

 [[ 81 133]]

 [[ 81

[[[173  25]]

 [[172  26]]

 [[171  26]]

 [[170  27]]

 [[169  27]]

 [[165  31]]

 [[164  31]]

 [[146  49]]

 [[146  50]]

 [[140  56]]

 [[140  57]]

 [[136  61]]

 [[136  62]]

 [[134  64]]

 [[133  64]]

 [[129  68]]

 [[128  68]]

 [[124  72]]

 [[123  72]]

 [[122  73]]

 [[121  73]]

 [[120  72]]

 [[120  64]]

 [[121  63]]

 [[121  59]]

 [[120  58]]

 [[120  55]]

 [[119  54]]

 [[119  51]]

 [[118  50]]

 [[118  47]]

 [[117  46]]

 [[117  45]]

 [[116  44]]

 [[116  43]]

 [[115  42]]

 [[115  41]]

 [[114  41]]

 [[113  40]]

 [[111  40]]

 [[109  42]]

 [[109  44]]

 [[108  45]]

 [[108  50]]

 [[107  51]]

 [[107  53]]

 [[106  54]]

 [[106  56]]

 [[105  57]]

 [[105  60]]

 [[104  61]]

 [[104  63]]

 [[103  64]]

 [[103  66]]

 [[102  67]]

 [[102  69]]

 [[101  70]]

 [[101  71]]

 [[100  72]]

 [[100  73]]

 [[ 99  74]]

 [[ 99  75]]

 [[ 98  76]]

 [[ 98  77]]

 [[ 97  78]]

 [[ 97  79]]

 [[ 96  80]]

 [[ 96  81]]

 [[ 95  82]]

 [[ 95  83]]

 [[ 94  84]]

 [[ 94

[[[168  20]]

 [[167  21]]

 [[165  21]]

 [[164  22]]

 [[163  22]]

 [[152  33]]

 [[152  34]]

 [[143  43]]

 [[143  44]]

 [[141  46]]

 [[141  47]]

 [[139  49]]

 [[139  50]]

 [[135  54]]

 [[135  55]]

 [[134  56]]

 [[134  57]]

 [[125  66]]

 [[124  66]]

 [[118  72]]

 [[117  72]]

 [[116  71]]

 [[116  67]]

 [[117  66]]

 [[117  56]]

 [[116  55]]

 [[116  53]]

 [[115  52]]

 [[115  50]]

 [[114  49]]

 [[114  45]]

 [[113  44]]

 [[113  42]]

 [[112  41]]

 [[112  40]]

 [[111  39]]

 [[111  38]]

 [[110  38]]

 [[109  37]]

 [[107  37]]

 [[105  39]]

 [[105  42]]

 [[104  43]]

 [[104  48]]

 [[103  49]]

 [[103  52]]

 [[102  53]]

 [[102  56]]

 [[101  57]]

 [[101  59]]

 [[100  60]]

 [[100  63]]

 [[ 99  64]]

 [[ 99  66]]

 [[ 98  67]]

 [[ 98  69]]

 [[ 97  70]]

 [[ 97  71]]

 [[ 96  72]]

 [[ 96  73]]

 [[ 95  74]]

 [[ 95  75]]

 [[ 94  76]]

 [[ 94  77]]

 [[ 93  78]]

 [[ 93  80]]

 [[ 92  81]]

 [[ 92  83]]

 [[ 91  84]]

 [[ 91  89]]

 [[ 92  90]]

 [[ 92

[[[161  20]]

 [[160  21]]

 [[159  21]]

 [[157  23]]

 [[156  23]]

 [[155  24]]

 [[155  25]]

 [[148  32]]

 [[148  33]]

 [[145  36]]

 [[145  37]]

 [[142  40]]

 [[142  41]]

 [[140  43]]

 [[140  44]]

 [[137  47]]

 [[137  48]]

 [[136  49]]

 [[136  50]]

 [[135  51]]

 [[135  52]]

 [[133  54]]

 [[133  55]]

 [[132  56]]

 [[132  57]]

 [[130  59]]

 [[130  60]]

 [[128  62]]

 [[128  63]]

 [[117  74]]

 [[116  74]]

 [[115  75]]

 [[113  75]]

 [[112  74]]

 [[112  59]]

 [[111  58]]

 [[111  55]]

 [[110  54]]

 [[110  52]]

 [[109  51]]

 [[109  48]]

 [[108  47]]

 [[108  45]]

 [[107  44]]

 [[107  43]]

 [[106  42]]

 [[106  41]]

 [[104  39]]

 [[102  39]]

 [[100  41]]

 [[100  43]]

 [[ 99  44]]

 [[ 99  52]]

 [[ 98  53]]

 [[ 98  56]]

 [[ 97  57]]

 [[ 97  61]]

 [[ 96  62]]

 [[ 96  65]]

 [[ 95  66]]

 [[ 95  69]]

 [[ 94  70]]

 [[ 94  72]]

 [[ 93  73]]

 [[ 93  75]]

 [[ 92  76]]

 [[ 92  77]]

 [[ 91  78]]

 [[ 91  80]]

 [[ 90  81]]

 [[ 90  82]]

 [[ 89

[[[163  26]]

 [[162  27]]

 [[161  27]]

 [[160  28]]

 [[159  28]]

 [[156  31]]

 [[155  31]]

 [[151  35]]

 [[151  36]]

 [[147  40]]

 [[147  41]]

 [[140  48]]

 [[140  49]]

 [[138  51]]

 [[138  52]]

 [[136  54]]

 [[136  55]]

 [[135  56]]

 [[135  57]]

 [[132  60]]

 [[132  61]]

 [[130  63]]

 [[130  64]]

 [[117  77]]

 [[116  77]]

 [[113  80]]

 [[112  80]]

 [[110  78]]

 [[110  63]]

 [[109  62]]

 [[109  60]]

 [[108  59]]

 [[108  57]]

 [[107  56]]

 [[107  53]]

 [[106  52]]

 [[106  49]]

 [[105  48]]

 [[105  47]]

 [[104  46]]

 [[104  45]]

 [[102  43]]

 [[ 99  43]]

 [[ 97  45]]

 [[ 97  55]]

 [[ 96  56]]

 [[ 96  60]]

 [[ 95  61]]

 [[ 95  66]]

 [[ 94  67]]

 [[ 94  70]]

 [[ 93  71]]

 [[ 93  74]]

 [[ 92  75]]

 [[ 92  77]]

 [[ 91  78]]

 [[ 91  80]]

 [[ 90  81]]

 [[ 90  82]]

 [[ 89  83]]

 [[ 89  85]]

 [[ 88  86]]

 [[ 88  89]]

 [[ 87  90]]

 [[ 87  91]]

 [[ 88  92]]

 [[ 88  97]]

 [[ 89  98]]

 [[ 89 104]]

 [[ 90 105]]

 [[ 90 111]]

 [[ 91

[[[160  27]]

 [[159  28]]

 [[158  28]]

 [[157  29]]

 [[156  29]]

 [[145  40]]

 [[145  41]]

 [[137  49]]

 [[137  50]]

 [[135  52]]

 [[135  53]]

 [[134  54]]

 [[134  55]]

 [[131  58]]

 [[131  59]]

 [[129  61]]

 [[129  62]]

 [[126  65]]

 [[126  66]]

 [[121  71]]

 [[120  71]]

 [[113  78]]

 [[112  78]]

 [[111  79]]

 [[110  79]]

 [[109  78]]

 [[109  77]]

 [[108  76]]

 [[108  70]]

 [[107  69]]

 [[107  63]]

 [[106  62]]

 [[106  59]]

 [[105  58]]

 [[105  54]]

 [[104  53]]

 [[104  50]]

 [[103  49]]

 [[103  48]]

 [[102  47]]

 [[102  46]]

 [[101  45]]

 [[101  44]]

 [[100  43]]

 [[ 97  43]]

 [[ 95  45]]

 [[ 95  54]]

 [[ 94  55]]

 [[ 94  60]]

 [[ 93  61]]

 [[ 93  65]]

 [[ 92  66]]

 [[ 92  70]]

 [[ 91  71]]

 [[ 91  74]]

 [[ 90  75]]

 [[ 90  78]]

 [[ 89  79]]

 [[ 89  80]]

 [[ 88  81]]

 [[ 88  82]]

 [[ 87  83]]

 [[ 87  86]]

 [[ 86  87]]

 [[ 86  97]]

 [[ 87  98]]

 [[ 87 104]]

 [[ 88 105]]

 [[ 88 109]]

 [[ 89 110]]

 [[ 89 116]]

 [[ 90

[[[159  25]]

 [[158  26]]

 [[157  26]]

 [[156  27]]

 [[155  27]]

 [[143  39]]

 [[143  40]]

 [[135  48]]

 [[135  49]]

 [[134  50]]

 [[134  51]]

 [[131  54]]

 [[131  55]]

 [[129  57]]

 [[129  58]]

 [[127  60]]

 [[127  61]]

 [[117  71]]

 [[117  72]]

 [[113  76]]

 [[112  76]]

 [[111  77]]

 [[110  77]]

 [[109  76]]

 [[109  70]]

 [[108  69]]

 [[108  61]]

 [[107  60]]

 [[107  59]]

 [[106  58]]

 [[106  52]]

 [[105  51]]

 [[105  48]]

 [[104  47]]

 [[104  45]]

 [[102  43]]

 [[102  42]]

 [[101  42]]

 [[100  41]]

 [[ 99  41]]

 [[ 97  43]]

 [[ 97  48]]

 [[ 96  49]]

 [[ 96  56]]

 [[ 95  57]]

 [[ 95  60]]

 [[ 94  61]]

 [[ 94  66]]

 [[ 93  67]]

 [[ 93  70]]

 [[ 92  71]]

 [[ 92  73]]

 [[ 91  74]]

 [[ 91  76]]

 [[ 90  77]]

 [[ 90  79]]

 [[ 89  80]]

 [[ 89  81]]

 [[ 88  82]]

 [[ 88  83]]

 [[ 87  84]]

 [[ 87  88]]

 [[ 86  89]]

 [[ 87  90]]

 [[ 87  96]]

 [[ 88  97]]

 [[ 88 102]]

 [[ 89 103]]

 [[ 89 108]]

 [[ 90 109]]

 [[ 90 113]]

 [[ 91

[[[158  25]]

 [[157  26]]

 [[156  26]]

 [[153  29]]

 [[152  29]]

 [[143  38]]

 [[143  39]]

 [[134  48]]

 [[134  49]]

 [[132  51]]

 [[132  52]]

 [[130  54]]

 [[130  55]]

 [[129  56]]

 [[129  57]]

 [[127  59]]

 [[127  60]]

 [[122  65]]

 [[122  66]]

 [[112  76]]

 [[111  76]]

 [[110  77]]

 [[108  75]]

 [[108  68]]

 [[107  67]]

 [[108  66]]

 [[108  63]]

 [[107  62]]

 [[107  60]]

 [[106  59]]

 [[106  55]]

 [[105  54]]

 [[105  50]]

 [[104  49]]

 [[104  47]]

 [[103  46]]

 [[103  44]]

 [[100  41]]

 [[ 98  41]]

 [[ 97  42]]

 [[ 97  44]]

 [[ 96  45]]

 [[ 96  53]]

 [[ 95  54]]

 [[ 95  58]]

 [[ 94  59]]

 [[ 94  63]]

 [[ 93  64]]

 [[ 93  68]]

 [[ 92  69]]

 [[ 92  72]]

 [[ 91  73]]

 [[ 91  75]]

 [[ 90  76]]

 [[ 90  77]]

 [[ 89  78]]

 [[ 89  80]]

 [[ 88  81]]

 [[ 88  82]]

 [[ 87  83]]

 [[ 87  85]]

 [[ 86  86]]

 [[ 86  94]]

 [[ 87  95]]

 [[ 87  98]]

 [[ 88  99]]

 [[ 88 104]]

 [[ 89 105]]

 [[ 89 108]]

 [[ 90 109]]

 [[ 90 114]]

 [[ 91

[[[157  26]]

 [[156  27]]

 [[155  27]]

 [[154  28]]

 [[153  28]]

 [[149  32]]

 [[148  32]]

 [[142  38]]

 [[142  39]]

 [[133  48]]

 [[133  49]]

 [[132  50]]

 [[132  51]]

 [[130  53]]

 [[130  54]]

 [[128  56]]

 [[128  57]]

 [[125  60]]

 [[125  61]]

 [[122  64]]

 [[122  65]]

 [[110  77]]

 [[109  77]]

 [[108  76]]

 [[108  70]]

 [[107  69]]

 [[107  63]]

 [[106  62]]

 [[106  61]]

 [[105  60]]

 [[105  54]]

 [[104  53]]

 [[104  50]]

 [[103  49]]

 [[103  46]]

 [[102  45]]

 [[102  44]]

 [[100  42]]

 [[ 97  42]]

 [[ 96  43]]

 [[ 96  48]]

 [[ 95  49]]

 [[ 95  55]]

 [[ 94  56]]

 [[ 94  60]]

 [[ 93  61]]

 [[ 93  66]]

 [[ 92  67]]

 [[ 92  70]]

 [[ 91  71]]

 [[ 91  73]]

 [[ 90  74]]

 [[ 90  75]]

 [[ 89  76]]

 [[ 89  77]]

 [[ 88  78]]

 [[ 88  81]]

 [[ 87  82]]

 [[ 87  83]]

 [[ 86  84]]

 [[ 86  86]]

 [[ 85  87]]

 [[ 85  92]]

 [[ 86  93]]

 [[ 86 100]]

 [[ 87 101]]

 [[ 87 105]]

 [[ 88 106]]

 [[ 88 109]]

 [[ 89 110]]

 [[ 89 118]]

 [[ 88

[[[157  29]]

 [[156  30]]

 [[155  30]]

 [[154  31]]

 [[153  31]]

 [[151  33]]

 [[150  33]]

 [[147  36]]

 [[146  36]]

 [[130  52]]

 [[130  53]]

 [[128  55]]

 [[128  56]]

 [[125  59]]

 [[125  60]]

 [[119  66]]

 [[119  67]]

 [[116  70]]

 [[115  70]]

 [[113  72]]

 [[113  73]]

 [[112  74]]

 [[111  74]]

 [[110  75]]

 [[109  74]]

 [[109  62]]

 [[108  61]]

 [[108  58]]

 [[107  57]]

 [[107  52]]

 [[106  51]]

 [[106  47]]

 [[105  46]]

 [[105  45]]

 [[104  44]]

 [[104  43]]

 [[102  41]]

 [[100  41]]

 [[ 98  43]]

 [[ 98  46]]

 [[ 97  47]]

 [[ 97  54]]

 [[ 96  55]]

 [[ 96  58]]

 [[ 95  59]]

 [[ 95  61]]

 [[ 94  62]]

 [[ 94  66]]

 [[ 93  67]]

 [[ 93  69]]

 [[ 92  70]]

 [[ 92  72]]

 [[ 91  73]]

 [[ 91  75]]

 [[ 90  76]]

 [[ 90  77]]

 [[ 89  78]]

 [[ 89  80]]

 [[ 88  81]]

 [[ 88  82]]

 [[ 87  83]]

 [[ 87  85]]

 [[ 86  86]]

 [[ 86  94]]

 [[ 87  95]]

 [[ 87 100]]

 [[ 88 101]]

 [[ 88 105]]

 [[ 89 106]]

 [[ 89 110]]

 [[ 90 111]]

 [[ 90

[[[155  31]]

 [[154  32]]

 [[153  32]]

 [[152  33]]

 [[151  33]]

 [[149  35]]

 [[148  35]]

 [[147  36]]

 [[146  36]]

 [[142  40]]

 [[142  41]]

 [[137  46]]

 [[136  46]]

 [[131  51]]

 [[131  52]]

 [[128  55]]

 [[128  56]]

 [[126  58]]

 [[126  59]]

 [[124  61]]

 [[124  62]]

 [[111  75]]

 [[109  73]]

 [[109  62]]

 [[108  61]]

 [[108  60]]

 [[107  59]]

 [[107  50]]

 [[106  49]]

 [[106  47]]

 [[105  46]]

 [[105  45]]

 [[104  44]]

 [[104  43]]

 [[103  42]]

 [[100  42]]

 [[ 99  43]]

 [[ 99  45]]

 [[ 98  46]]

 [[ 98  53]]

 [[ 97  54]]

 [[ 97  57]]

 [[ 96  58]]

 [[ 96  61]]

 [[ 95  62]]

 [[ 95  65]]

 [[ 94  66]]

 [[ 94  69]]

 [[ 93  70]]

 [[ 93  71]]

 [[ 92  72]]

 [[ 92  74]]

 [[ 91  75]]

 [[ 91  76]]

 [[ 90  77]]

 [[ 90  79]]

 [[ 89  80]]

 [[ 89  81]]

 [[ 88  82]]

 [[ 88  84]]

 [[ 87  85]]

 [[ 87  86]]

 [[ 86  87]]

 [[ 86  92]]

 [[ 87  93]]

 [[ 87  99]]

 [[ 88 100]]

 [[ 88 106]]

 [[ 89 107]]

 [[ 89 111]]

 [[ 90 112]]

 [[ 90

[[[158  30]]

 [[157  31]]

 [[155  31]]

 [[152  34]]

 [[151  34]]

 [[149  36]]

 [[148  36]]

 [[131  53]]

 [[131  54]]

 [[129  56]]

 [[129  57]]

 [[126  60]]

 [[126  61]]

 [[123  64]]

 [[123  65]]

 [[112  76]]

 [[111  76]]

 [[110  77]]

 [[108  75]]

 [[108  65]]

 [[107  64]]

 [[107  60]]

 [[106  59]]

 [[106  50]]

 [[105  49]]

 [[105  47]]

 [[104  46]]

 [[104  45]]

 [[103  44]]

 [[103  43]]

 [[102  43]]

 [[101  42]]

 [[100  42]]

 [[ 99  43]]

 [[ 99  44]]

 [[ 98  45]]

 [[ 98  49]]

 [[ 97  50]]

 [[ 97  55]]

 [[ 96  56]]

 [[ 96  59]]

 [[ 95  60]]

 [[ 95  63]]

 [[ 94  64]]

 [[ 94  68]]

 [[ 93  69]]

 [[ 93  70]]

 [[ 92  71]]

 [[ 92  73]]

 [[ 91  74]]

 [[ 91  77]]

 [[ 90  78]]

 [[ 90  79]]

 [[ 88  81]]

 [[ 88  83]]

 [[ 87  84]]

 [[ 87  86]]

 [[ 86  87]]

 [[ 86  95]]

 [[ 87  96]]

 [[ 87 103]]

 [[ 88 104]]

 [[ 88 108]]

 [[ 89 109]]

 [[ 89 119]]

 [[ 87 121]]

 [[ 87 122]]

 [[ 86 123]]

 [[ 86 124]]

 [[ 85 125]]

 [[ 85 126]]

 [[ 84

[[[164  30]]

 [[163  31]]

 [[162  31]]

 [[161  32]]

 [[160  32]]

 [[159  33]]

 [[158  33]]

 [[156  35]]

 [[155  35]]

 [[149  41]]

 [[148  41]]

 [[138  51]]

 [[138  52]]

 [[135  55]]

 [[135  56]]

 [[132  59]]

 [[131  59]]

 [[130  58]]

 [[130  54]]

 [[129  53]]

 [[129  51]]

 [[128  50]]

 [[128  49]]

 [[126  47]]

 [[124  47]]

 [[123  48]]

 [[122  48]]

 [[120  50]]

 [[120  51]]

 [[119  52]]

 [[119  54]]

 [[118  55]]

 [[118  57]]

 [[117  58]]

 [[117  60]]

 [[116  61]]

 [[116  62]]

 [[115  63]]

 [[115  64]]

 [[113  66]]

 [[113  67]]

 [[112  68]]

 [[112  70]]

 [[110  72]]

 [[110  73]]

 [[108  75]]

 [[108  76]]

 [[107  77]]

 [[107  79]]

 [[105  81]]

 [[105  82]]

 [[103  84]]

 [[103  85]]

 [[102  86]]

 [[102  87]]

 [[101  88]]

 [[101  90]]

 [[100  91]]

 [[100  94]]

 [[ 99  95]]

 [[ 99 101]]

 [[ 98 102]]

 [[ 98 107]]

 [[ 97 108]]

 [[ 97 110]]

 [[ 96 111]]

 [[ 96 112]]

 [[ 95 113]]

 [[ 95 114]]

 [[ 94 115]]

 [[ 94 116]]

 [[ 93

[[[166  33]]

 [[165  34]]

 [[163  34]]

 [[162  35]]

 [[160  35]]

 [[159  36]]

 [[158  36]]

 [[157  37]]

 [[156  37]]

 [[155  38]]

 [[154  38]]

 [[149  43]]

 [[148  43]]

 [[143  48]]

 [[142  48]]

 [[138  52]]

 [[138  53]]

 [[136  55]]

 [[136  56]]

 [[135  57]]

 [[135  58]]

 [[133  60]]

 [[133  61]]

 [[131  63]]

 [[131  64]]

 [[130  65]]

 [[130  66]]

 [[129  67]]

 [[129  68]]

 [[128  69]]

 [[128  70]]

 [[127  71]]

 [[127  72]]

 [[123  76]]

 [[123  77]]

 [[120  80]]

 [[120  81]]

 [[119  82]]

 [[119  83]]

 [[117  85]]

 [[117  86]]

 [[112  91]]

 [[112  92]]

 [[109  95]]

 [[109  96]]

 [[106  99]]

 [[106 100]]

 [[103 103]]

 [[103 104]]

 [[ 96 111]]

 [[ 96 112]]

 [[ 85 123]]

 [[ 85 124]]

 [[ 84 125]]

 [[ 83 125]]

 [[ 83 126]]

 [[ 78 131]]

 [[ 78 132]]

 [[ 76 134]]

 [[ 76 135]]

 [[ 73 138]]

 [[ 73 139]]

 [[ 68 144]]

 [[ 67 144]]

 [[ 65 146]]

 [[ 61 146]]

 [[ 59 148]]

 [[ 59 155]]

 [[ 58 156]]

 [[ 58 157]]

 [[ 56 159]]

 [[ 56

[[[171  35]]

 [[170  36]]

 [[169  36]]

 [[168  37]]

 [[167  37]]

 [[166  38]]

 [[165  38]]

 [[164  39]]

 [[163  39]]

 [[160  42]]

 [[159  42]]

 [[156  45]]

 [[155  45]]

 [[150  50]]

 [[149  50]]

 [[147  52]]

 [[146  52]]

 [[144  54]]

 [[144  55]]

 [[142  57]]

 [[142  58]]

 [[140  60]]

 [[140  61]]

 [[139  62]]

 [[139  63]]

 [[136  66]]

 [[136  67]]

 [[135  68]]

 [[135  69]]

 [[134  70]]

 [[134  71]]

 [[132  73]]

 [[132  74]]

 [[130  76]]

 [[130  77]]

 [[127  80]]

 [[127  81]]

 [[122  86]]

 [[122  87]]

 [[117  92]]

 [[117  93]]

 [[110 100]]

 [[110 101]]

 [[ 93 118]]

 [[ 93 119]]

 [[ 91 121]]

 [[ 90 121]]

 [[ 75 136]]

 [[ 75 137]]

 [[ 73 139]]

 [[ 73 140]]

 [[ 69 144]]

 [[ 68 144]]

 [[ 66 146]]

 [[ 64 146]]

 [[ 62 148]]

 [[ 62 150]]

 [[ 61 151]]

 [[ 61 153]]

 [[ 59 155]]

 [[ 59 156]]

 [[ 58 157]]

 [[ 58 158]]

 [[ 52 164]]

 [[ 52 165]]

 [[ 37 180]]

 [[ 37 181]]

 [[ 34 184]]

 [[ 33 184]]

 [[ 17 200]]

 [[ 16 200]]

 [[ 13

[[[174  34]]

 [[173  35]]

 [[172  35]]

 [[171  36]]

 [[170  36]]

 [[169  37]]

 [[168  37]]

 [[166  39]]

 [[165  39]]

 [[164  40]]

 [[163  40]]

 [[157  46]]

 [[156  46]]

 [[143  59]]

 [[142  59]]

 [[138  63]]

 [[137  63]]

 [[133  67]]

 [[133  68]]

 [[132  69]]

 [[132  70]]

 [[130  72]]

 [[130  73]]

 [[124  79]]

 [[123  79]]

 [[121  81]]

 [[121  82]]

 [[120  83]]

 [[120  86]]

 [[119  87]]

 [[119  89]]

 [[118  90]]

 [[118  91]]

 [[117  92]]

 [[117  94]]

 [[115  96]]

 [[115  97]]

 [[112 100]]

 [[111 100]]

 [[106 105]]

 [[106 106]]

 [[ 93 119]]

 [[ 92 119]]

 [[ 87 124]]

 [[ 86 124]]

 [[ 84 126]]

 [[ 83 126]]

 [[ 81 128]]

 [[ 80 128]]

 [[ 73 135]]

 [[ 73 136]]

 [[ 72 137]]

 [[ 72 138]]

 [[ 71 139]]

 [[ 71 140]]

 [[ 70 141]]

 [[ 70 142]]

 [[ 64 148]]

 [[ 64 149]]

 [[ 61 152]]

 [[ 60 152]]

 [[ 59 153]]

 [[ 59 154]]

 [[ 58 155]]

 [[ 58 157]]

 [[ 37 178]]

 [[ 37 179]]

 [[ 36 180]]

 [[ 35 180]]

 [[ 20 195]]

 [[ 19 195]]

 [[  1

[[[179  31]]

 [[178  32]]

 [[176  32]]

 [[175  33]]

 [[174  33]]

 [[170  37]]

 [[169  37]]

 [[167  39]]

 [[165  39]]

 [[164  40]]

 [[163  40]]

 [[162  41]]

 [[161  41]]

 [[159  43]]

 [[158  43]]

 [[156  45]]

 [[155  45]]

 [[153  47]]

 [[152  47]]

 [[150  49]]

 [[149  49]]

 [[146  52]]

 [[145  52]]

 [[140  57]]

 [[139  57]]

 [[138  58]]

 [[136  58]]

 [[135  59]]

 [[134  59]]

 [[133  60]]

 [[132  60]]

 [[131  61]]

 [[130  61]]

 [[129  62]]

 [[128  62]]

 [[125  65]]

 [[124  65]]

 [[122  67]]

 [[122  68]]

 [[117  73]]

 [[117  74]]

 [[116  75]]

 [[116  80]]

 [[115  81]]

 [[115  85]]

 [[114  86]]

 [[114  94]]

 [[113  95]]

 [[113  96]]

 [[112  97]]

 [[112  98]]

 [[108 102]]

 [[107 102]]

 [[105 104]]

 [[105 105]]

 [[ 91 119]]

 [[ 90 119]]

 [[ 88 121]]

 [[ 87 121]]

 [[ 84 124]]

 [[ 83 124]]

 [[ 82 125]]

 [[ 81 125]]

 [[ 74 132]]

 [[ 74 133]]

 [[ 73 134]]

 [[ 73 135]]

 [[ 72 136]]

 [[ 72 137]]

 [[ 71 138]]

 [[ 71 139]]

 [[ 70

[[[179  24]]

 [[178  25]]

 [[177  25]]

 [[172  30]]

 [[171  30]]

 [[169  32]]

 [[168  32]]

 [[166  34]]

 [[164  32]]

 [[164  31]]

 [[163  31]]

 [[162  30]]

 [[160  30]]

 [[159  31]]

 [[158  31]]

 [[156  33]]

 [[155  33]]

 [[153  35]]

 [[152  35]]

 [[150  37]]

 [[149  37]]

 [[135  51]]

 [[135  52]]

 [[133  54]]

 [[133  55]]

 [[132  56]]

 [[132  57]]

 [[131  58]]

 [[131  59]]

 [[129  61]]

 [[129  62]]

 [[128  63]]

 [[128  65]]

 [[127  66]]

 [[127  68]]

 [[126  69]]

 [[126  70]]

 [[125  71]]

 [[124  71]]

 [[123  70]]

 [[123  64]]

 [[124  63]]

 [[124  60]]

 [[125  59]]

 [[125  57]]

 [[126  56]]

 [[126  54]]

 [[128  52]]

 [[128  51]]

 [[129  50]]

 [[129  44]]

 [[128  43]]

 [[125  43]]

 [[119  49]]

 [[118  49]]

 [[118  50]]

 [[115  53]]

 [[115  54]]

 [[114  55]]

 [[114  56]]

 [[113  57]]

 [[113  58]]

 [[112  59]]

 [[112  60]]

 [[111  61]]

 [[111  63]]

 [[110  64]]

 [[110  87]]

 [[109  88]]

 [[109  89]]

 [[108  90]]

 [[108

[[[184  22]]

 [[183  23]]

 [[182  23]]

 [[180  25]]

 [[179  25]]

 [[174  30]]

 [[173  30]]

 [[173  31]]

 [[170  34]]

 [[168  32]]

 [[169  31]]

 [[169  30]]

 [[168  29]]

 [[168  28]]

 [[166  26]]

 [[163  26]]

 [[161  28]]

 [[160  28]]

 [[158  30]]

 [[157  30]]

 [[155  32]]

 [[154  32]]

 [[147  39]]

 [[146  39]]

 [[145  40]]

 [[145  41]]

 [[139  47]]

 [[139  48]]

 [[137  50]]

 [[137  51]]

 [[136  52]]

 [[136  53]]

 [[135  54]]

 [[135  55]]

 [[134  56]]

 [[134  57]]

 [[133  58]]

 [[133  59]]

 [[132  60]]

 [[132  61]]

 [[131  62]]

 [[131  64]]

 [[130  65]]

 [[130  66]]

 [[129  67]]

 [[129  68]]

 [[128  69]]

 [[127  68]]

 [[127  66]]

 [[126  65]]

 [[126  57]]

 [[127  56]]

 [[127  53]]

 [[128  52]]

 [[128  51]]

 [[129  50]]

 [[129  49]]

 [[130  48]]

 [[130  47]]

 [[131  46]]

 [[131  44]]

 [[132  43]]

 [[132  38]]

 [[130  36]]

 [[129  36]]

 [[128  37]]

 [[127  37]]

 [[121  43]]

 [[121  44]]

 [[118  47]]

 [[118  48]]

 [[117

[[[193  24]]

 [[192  25]]

 [[191  25]]

 [[190  26]]

 [[189  26]]

 [[188  27]]

 [[187  27]]

 [[183  31]]

 [[182  31]]

 [[180  33]]

 [[178  33]]

 [[177  32]]

 [[177  31]]

 [[176  30]]

 [[176  29]]

 [[175  29]]

 [[174  28]]

 [[172  28]]

 [[171  29]]

 [[170  29]]

 [[169  30]]

 [[168  30]]

 [[167  31]]

 [[166  31]]

 [[165  32]]

 [[164  32]]

 [[162  34]]

 [[161  34]]

 [[158  37]]

 [[157  37]]

 [[144  50]]

 [[144  51]]

 [[142  53]]

 [[142  54]]

 [[141  55]]

 [[141  56]]

 [[140  57]]

 [[140  58]]

 [[139  59]]

 [[139  60]]

 [[138  61]]

 [[138  62]]

 [[137  63]]

 [[137  64]]

 [[135  66]]

 [[134  66]]

 [[133  65]]

 [[133  61]]

 [[134  60]]

 [[134  56]]

 [[135  55]]

 [[135  53]]

 [[136  52]]

 [[136  51]]

 [[137  50]]

 [[137  49]]

 [[139  47]]

 [[139  46]]

 [[140  45]]

 [[140  43]]

 [[141  42]]

 [[141  41]]

 [[142  40]]

 [[142  38]]

 [[141  37]]

 [[141  36]]

 [[136  36]]

 [[132  40]]

 [[131  40]]

 [[127  44]]

 [[127  45]]

 [[125

[[[203  34]]

 [[202  35]]

 [[198  35]]

 [[197  36]]

 [[194  36]]

 [[193  37]]

 [[192  37]]

 [[191  38]]

 [[175  38]]

 [[174  39]]

 [[171  39]]

 [[170  40]]

 [[169  40]]

 [[168  41]]

 [[160  41]]

 [[159  40]]

 [[149  40]]

 [[148  41]]

 [[146  41]]

 [[145  42]]

 [[144  42]]

 [[143  43]]

 [[142  43]]

 [[140  45]]

 [[139  45]]

 [[134  50]]

 [[134  52]]

 [[133  53]]

 [[133  55]]

 [[132  56]]

 [[132  58]]

 [[131  59]]

 [[131  64]]

 [[130  65]]

 [[130  67]]

 [[129  68]]

 [[129  70]]

 [[128  71]]

 [[128  72]]

 [[127  73]]

 [[127  74]]

 [[126  75]]

 [[126  76]]

 [[124  78]]

 [[124  79]]

 [[121  82]]

 [[121  83]]

 [[119  85]]

 [[119  86]]

 [[117  88]]

 [[117  89]]

 [[116  90]]

 [[116  91]]

 [[115  92]]

 [[115  93]]

 [[113  95]]

 [[113  96]]

 [[111  98]]

 [[111  99]]

 [[110 100]]

 [[110 101]]

 [[105 106]]

 [[105 107]]

 [[103 109]]

 [[102 109]]

 [[100 111]]

 [[ 99 111]]

 [[ 97 113]]

 [[ 96 113]]

 [[ 88 121]]

 [[ 88 122]]

 [[ 87

[[[212  36]]

 [[211  37]]

 [[203  37]]

 [[202  38]]

 [[199  38]]

 [[198  39]]

 [[196  39]]

 [[195  40]]

 [[194  40]]

 [[193  41]]

 [[186  41]]

 [[185  42]]

 [[181  42]]

 [[180  43]]

 [[177  43]]

 [[176  44]]

 [[171  44]]

 [[170  45]]

 [[160  45]]

 [[159  46]]

 [[156  46]]

 [[155  47]]

 [[154  47]]

 [[153  48]]

 [[151  48]]

 [[148  51]]

 [[148  52]]

 [[147  53]]

 [[147  55]]

 [[146  56]]

 [[146  58]]

 [[145  59]]

 [[145  62]]

 [[144  63]]

 [[144  67]]

 [[143  68]]

 [[143  71]]

 [[142  72]]

 [[142  74]]

 [[141  75]]

 [[141  77]]

 [[140  78]]

 [[140  80]]

 [[138  82]]

 [[138  83]]

 [[136  85]]

 [[136  86]]

 [[134  88]]

 [[134  89]]

 [[133  90]]

 [[133  91]]

 [[132  92]]

 [[132  93]]

 [[131  94]]

 [[131  95]]

 [[130  96]]

 [[130  97]]

 [[129  98]]

 [[129  99]]

 [[128 100]]

 [[128 101]]

 [[127 102]]

 [[127 103]]

 [[126 104]]

 [[126 105]]

 [[125 106]]

 [[125 107]]

 [[123 109]]

 [[123 110]]

 [[116 117]]

 [[115 117]]

 [[113

[[[195  33]]

 [[194  34]]

 [[188  34]]

 [[187  35]]

 [[185  35]]

 [[184  36]]

 [[182  36]]

 [[181  37]]

 [[178  37]]

 [[177  38]]

 [[172  38]]

 [[171  39]]

 [[169  39]]

 [[168  40]]

 [[163  40]]

 [[162  41]]

 [[158  41]]

 [[157  42]]

 [[154  42]]

 [[153  43]]

 [[151  43]]

 [[150  44]]

 [[147  44]]

 [[146  45]]

 [[144  45]]

 [[141  48]]

 [[141  50]]

 [[140  51]]

 [[140  53]]

 [[139  54]]

 [[139  56]]

 [[138  57]]

 [[138  61]]

 [[137  62]]

 [[137  66]]

 [[136  67]]

 [[136  69]]

 [[135  70]]

 [[135  73]]

 [[134  74]]

 [[134  75]]

 [[133  76]]

 [[133  77]]

 [[131  79]]

 [[131  80]]

 [[130  81]]

 [[130  82]]

 [[129  83]]

 [[129  84]]

 [[128  85]]

 [[128  86]]

 [[127  87]]

 [[127  88]]

 [[126  89]]

 [[126  90]]

 [[125  91]]

 [[125  92]]

 [[124  93]]

 [[124  94]]

 [[123  95]]

 [[123  96]]

 [[122  97]]

 [[122  99]]

 [[121 100]]

 [[121 101]]

 [[120 102]]

 [[120 103]]

 [[119 104]]

 [[119 105]]

 [[114 110]]

 [[113 110]]

 [[107

[[[212  18]]

 [[211  19]]

 [[207  19]]

 [[206  20]]

 [[204  20]]

 [[203  21]]

 [[201  21]]

 [[200  22]]

 [[199  22]]

 [[198  23]]

 [[195  23]]

 [[194  24]]

 [[192  24]]

 [[191  25]]

 [[189  25]]

 [[188  26]]

 [[185  26]]

 [[184  27]]

 [[181  27]]

 [[180  28]]

 [[177  28]]

 [[176  29]]

 [[174  29]]

 [[173  30]]

 [[171  30]]

 [[170  31]]

 [[167  31]]

 [[165  33]]

 [[164  33]]

 [[163  34]]

 [[163  35]]

 [[162  36]]

 [[162  37]]

 [[161  38]]

 [[161  41]]

 [[160  42]]

 [[160  43]]

 [[159  44]]

 [[159  46]]

 [[158  47]]

 [[158  52]]

 [[157  53]]

 [[157  56]]

 [[156  57]]

 [[156  59]]

 [[155  60]]

 [[155  63]]

 [[154  64]]

 [[154  65]]

 [[153  66]]

 [[153  67]]

 [[152  68]]

 [[152  69]]

 [[151  70]]

 [[151  71]]

 [[149  73]]

 [[149  75]]

 [[148  76]]

 [[148  77]]

 [[147  78]]

 [[147  79]]

 [[146  80]]

 [[146  81]]

 [[145  82]]

 [[145  83]]

 [[144  84]]

 [[144  86]]

 [[143  87]]

 [[143  89]]

 [[142  90]]

 [[142  91]]

 [[141

[[[201   6]]

 [[200   7]]

 [[198   7]]

 [[197   8]]

 [[195   8]]

 [[194   9]]

 [[191   9]]

 [[190  10]]

 [[189  10]]

 [[188  11]]

 [[187  11]]

 [[186  12]]

 [[185  12]]

 [[184  13]]

 [[182  13]]

 [[181  14]]

 [[178  14]]

 [[177  15]]

 [[175  15]]

 [[174  16]]

 [[172  16]]

 [[171  17]]

 [[169  17]]

 [[168  18]]

 [[167  18]]

 [[166  19]]

 [[165  19]]

 [[164  20]]

 [[163  20]]

 [[162  21]]

 [[161  21]]

 [[160  22]]

 [[160  23]]

 [[159  24]]

 [[159  25]]

 [[158  26]]

 [[158  30]]

 [[157  31]]

 [[157  33]]

 [[156  34]]

 [[156  40]]

 [[157  41]]

 [[156  42]]

 [[156  45]]

 [[155  46]]

 [[155  52]]

 [[154  53]]

 [[154  55]]

 [[153  56]]

 [[153  57]]

 [[152  58]]

 [[152  59]]

 [[151  60]]

 [[151  63]]

 [[150  64]]

 [[150  68]]

 [[149  69]]

 [[149  71]]

 [[148  72]]

 [[148  75]]

 [[147  76]]

 [[147  79]]

 [[146  80]]

 [[146  81]]

 [[145  82]]

 [[145  83]]

 [[144  84]]

 [[144  86]]

 [[142  88]]

 [[141  88]]

 [[137  92]]

 [[137

[[[159   0]]

 [[159   1]]

 [[155   5]]

 [[154   5]]

 [[153   6]]

 [[152   6]]

 [[149   9]]

 [[149  10]]

 [[146  13]]

 [[145  13]]

 [[144  14]]

 [[143  14]]

 [[141  16]]

 [[141  17]]

 [[140  18]]

 [[140  20]]

 [[139  21]]

 [[139  24]]

 [[138  25]]

 [[138  36]]

 [[137  37]]

 [[137  43]]

 [[136  44]]

 [[136  64]]

 [[135  65]]

 [[135  77]]

 [[134  78]]

 [[134  80]]

 [[133  81]]

 [[133  82]]

 [[127  88]]

 [[127  89]]

 [[126  90]]

 [[126  91]]

 [[125  92]]

 [[125  93]]

 [[124  94]]

 [[124  95]]

 [[123  96]]

 [[123  97]]

 [[122  98]]

 [[122  99]]

 [[121 100]]

 [[121 101]]

 [[120 102]]

 [[120 103]]

 [[116 107]]

 [[115 107]]

 [[114 108]]

 [[114 109]]

 [[112 111]]

 [[112 112]]

 [[109 115]]

 [[109 116]]

 [[ 67 158]]

 [[ 66 158]]

 [[ 57 167]]

 [[ 56 167]]

 [[ 38 185]]

 [[ 38 186]]

 [[ 33 191]]

 [[ 33 192]]

 [[ 29 196]]

 [[ 29 197]]

 [[ 26 200]]

 [[ 26 201]]

 [[ 24 203]]

 [[ 24 204]]

 [[ 21 207]]

 [[ 21 208]]

 [[ 17 212]]

 [[ 17

[[[184   2]]

 [[183   3]]

 [[179   3]]

 [[178   4]]

 [[176   4]]

 [[175   5]]

 [[174   5]]

 [[173   6]]

 [[171   6]]

 [[170   7]]

 [[169   7]]

 [[168   8]]

 [[166   8]]

 [[165   9]]

 [[164   9]]

 [[163  10]]

 [[162  10]]

 [[161  11]]

 [[161  12]]

 [[159  14]]

 [[158  14]]

 [[157  15]]

 [[156  15]]

 [[153  18]]

 [[153  19]]

 [[152  20]]

 [[152  21]]

 [[151  22]]

 [[151  23]]

 [[147  27]]

 [[147  28]]

 [[146  29]]

 [[146  31]]

 [[145  32]]

 [[145  35]]

 [[144  36]]

 [[144  38]]

 [[143  39]]

 [[143  43]]

 [[142  44]]

 [[142  47]]

 [[141  48]]

 [[141  52]]

 [[140  53]]

 [[140  60]]

 [[139  61]]

 [[139  66]]

 [[138  67]]

 [[138  73]]

 [[137  74]]

 [[137  77]]

 [[136  78]]

 [[136  85]]

 [[135  86]]

 [[135  88]]

 [[134  89]]

 [[134  90]]

 [[130  94]]

 [[129  94]]

 [[127  96]]

 [[127  97]]

 [[124 100]]

 [[124 101]]

 [[123 102]]

 [[123 103]]

 [[122 104]]

 [[122 105]]

 [[121 106]]

 [[121 107]]

 [[119 109]]

 [[119 110]]

 [[118

[[[184   6]]

 [[183   7]]

 [[180   7]]

 [[179   8]]

 [[177   8]]

 [[176   9]]

 [[174   9]]

 [[173  10]]

 [[172  10]]

 [[171  11]]

 [[168  11]]

 [[167  12]]

 [[166  12]]

 [[165  13]]

 [[164  13]]

 [[162  15]]

 [[162  16]]

 [[161  17]]

 [[161  18]]

 [[160  19]]

 [[160  21]]

 [[159  22]]

 [[159  23]]

 [[158  24]]

 [[158  25]]

 [[157  26]]

 [[157  28]]

 [[156  29]]

 [[156  31]]

 [[154  33]]

 [[154  35]]

 [[153  36]]

 [[153  40]]

 [[152  41]]

 [[152  44]]

 [[151  45]]

 [[151  46]]

 [[150  47]]

 [[150  49]]

 [[149  50]]

 [[149  51]]

 [[148  52]]

 [[148  53]]

 [[147  54]]

 [[147  58]]

 [[146  59]]

 [[146  61]]

 [[145  62]]

 [[145  65]]

 [[144  66]]

 [[144  67]]

 [[143  68]]

 [[143  70]]

 [[142  71]]

 [[142  73]]

 [[141  74]]

 [[141  75]]

 [[140  76]]

 [[140  78]]

 [[139  79]]

 [[139  80]]

 [[138  81]]

 [[138  82]]

 [[137  83]]

 [[137  85]]

 [[136  86]]

 [[136  87]]

 [[135  88]]

 [[135  90]]

 [[128  97]]

 [[127  97]]

 [[121

[[[171   8]]

 [[170   9]]

 [[166   9]]

 [[165  10]]

 [[162  10]]

 [[161  11]]

 [[158  11]]

 [[157  12]]

 [[155  12]]

 [[154  13]]

 [[152  13]]

 [[149  16]]

 [[149  17]]

 [[148  18]]

 [[148  20]]

 [[147  21]]

 [[147  22]]

 [[146  23]]

 [[146  24]]

 [[145  25]]

 [[145  26]]

 [[144  27]]

 [[144  28]]

 [[143  29]]

 [[143  32]]

 [[142  33]]

 [[142  35]]

 [[141  36]]

 [[141  38]]

 [[140  39]]

 [[140  40]]

 [[139  41]]

 [[139  42]]

 [[138  43]]

 [[138  44]]

 [[137  45]]

 [[137  46]]

 [[136  47]]

 [[136  48]]

 [[135  49]]

 [[135  50]]

 [[134  51]]

 [[134  54]]

 [[133  55]]

 [[133  60]]

 [[132  61]]

 [[132  64]]

 [[131  65]]

 [[131  69]]

 [[130  70]]

 [[130  72]]

 [[129  73]]

 [[129  76]]

 [[128  77]]

 [[128  78]]

 [[127  79]]

 [[127  82]]

 [[126  83]]

 [[126  86]]

 [[125  87]]

 [[125  88]]

 [[124  89]]

 [[124  91]]

 [[118  97]]

 [[117  97]]

 [[114 100]]

 [[114 101]]

 [[112 103]]

 [[112 104]]

 [[110 106]]

 [[110 107]]

 [[107

[[[168   0]]

 [[164   4]]

 [[163   4]]

 [[149  18]]

 [[149  19]]

 [[148  20]]

 [[148  22]]

 [[146  24]]

 [[146  25]]

 [[144  27]]

 [[144  28]]

 [[143  29]]

 [[143  30]]

 [[142  31]]

 [[142  32]]

 [[141  33]]

 [[141  34]]

 [[139  36]]

 [[139  37]]

 [[137  39]]

 [[137  43]]

 [[136  44]]

 [[136  46]]

 [[135  47]]

 [[135  51]]

 [[134  52]]

 [[134  56]]

 [[133  57]]

 [[133  63]]

 [[132  64]]

 [[132  67]]

 [[131  68]]

 [[131  70]]

 [[130  71]]

 [[130  73]]

 [[129  74]]

 [[129  76]]

 [[128  77]]

 [[128  78]]

 [[127  79]]

 [[127  83]]

 [[126  84]]

 [[126  86]]

 [[125  87]]

 [[125  89]]

 [[124  90]]

 [[124  91]]

 [[123  92]]

 [[123  93]]

 [[122  94]]

 [[122  95]]

 [[120  97]]

 [[119  97]]

 [[112 104]]

 [[112 105]]

 [[111 106]]

 [[111 107]]

 [[109 109]]

 [[109 110]]

 [[108 111]]

 [[108 112]]

 [[101 119]]

 [[100 119]]

 [[ 96 123]]

 [[ 96 124]]

 [[ 91 129]]

 [[ 90 129]]

 [[ 87 132]]

 [[ 86 132]]

 [[ 80 138]]

 [[ 79 138]]

 [[ 75

[[[163   0]]

 [[163   2]]

 [[162   3]]

 [[162   4]]

 [[161   5]]

 [[161   6]]

 [[158   9]]

 [[158  10]]

 [[156  12]]

 [[156  13]]

 [[155  14]]

 [[155  15]]

 [[152  18]]

 [[152  19]]

 [[151  20]]

 [[150  20]]

 [[146  24]]

 [[146  25]]

 [[145  26]]

 [[145  27]]

 [[144  28]]

 [[144  29]]

 [[143  30]]

 [[143  31]]

 [[142  32]]

 [[142  33]]

 [[141  34]]

 [[141  35]]

 [[140  36]]

 [[140  37]]

 [[139  38]]

 [[139  40]]

 [[138  41]]

 [[138  42]]

 [[137  43]]

 [[137  53]]

 [[136  54]]

 [[136  59]]

 [[137  60]]

 [[137  63]]

 [[136  64]]

 [[136  73]]

 [[135  74]]

 [[135  76]]

 [[134  77]]

 [[134  81]]

 [[133  82]]

 [[133  85]]

 [[132  86]]

 [[132  88]]

 [[131  89]]

 [[131  93]]

 [[130  94]]

 [[130  96]]

 [[129  97]]

 [[129  98]]

 [[121 106]]

 [[120 106]]

 [[118 108]]

 [[118 109]]

 [[116 111]]

 [[116 112]]

 [[114 114]]

 [[114 115]]

 [[113 116]]

 [[113 117]]

 [[107 123]]

 [[106 123]]

 [[103 126]]

 [[103 127]]

 [[ 97 133]]

 [[ 96

[[[176   0]]

 [[175   1]]

 [[175   3]]

 [[174   4]]

 [[174   5]]

 [[171   8]]

 [[171   9]]

 [[168  12]]

 [[168  13]]

 [[161  20]]

 [[161  21]]

 [[160  22]]

 [[160  23]]

 [[158  25]]

 [[158  26]]

 [[157  27]]

 [[157  28]]

 [[155  30]]

 [[155  32]]

 [[153  34]]

 [[153  35]]

 [[151  37]]

 [[151  38]]

 [[148  41]]

 [[148  42]]

 [[146  44]]

 [[146  46]]

 [[145  47]]

 [[145  48]]

 [[144  49]]

 [[144  50]]

 [[143  51]]

 [[143  52]]

 [[142  53]]

 [[142  59]]

 [[143  60]]

 [[143  64]]

 [[144  65]]

 [[144  68]]

 [[145  69]]

 [[145  71]]

 [[146  72]]

 [[146  75]]

 [[147  76]]

 [[147  78]]

 [[146  79]]

 [[146  82]]

 [[145  83]]

 [[145  85]]

 [[144  86]]

 [[144  87]]

 [[143  88]]

 [[143  90]]

 [[142  91]]

 [[142  93]]

 [[141  94]]

 [[141  95]]

 [[140  96]]

 [[140  97]]

 [[139  98]]

 [[139  99]]

 [[138 100]]

 [[138 102]]

 [[136 104]]

 [[136 105]]

 [[131 110]]

 [[130 110]]

 [[128 112]]

 [[127 112]]

 [[122 117]]

 [[122 118]]

 [[121

[[[175   0]]

 [[175   2]]

 [[173   4]]

 [[173   5]]

 [[172   6]]

 [[172   7]]

 [[171   8]]

 [[171   9]]

 [[170  10]]

 [[170  11]]

 [[168  13]]

 [[168  14]]

 [[167  15]]

 [[167  16]]

 [[160  23]]

 [[160  24]]

 [[157  27]]

 [[157  28]]

 [[156  29]]

 [[156  30]]

 [[154  32]]

 [[154  33]]

 [[152  35]]

 [[152  36]]

 [[149  39]]

 [[149  40]]

 [[147  42]]

 [[147  43]]

 [[146  44]]

 [[146  45]]

 [[144  47]]

 [[144  48]]

 [[143  49]]

 [[143  50]]

 [[142  51]]

 [[142  54]]

 [[143  55]]

 [[143  58]]

 [[144  59]]

 [[144  61]]

 [[145  62]]

 [[145  65]]

 [[146  66]]

 [[146  67]]

 [[147  68]]

 [[147  69]]

 [[148  70]]

 [[148  77]]

 [[147  78]]

 [[147  79]]

 [[146  80]]

 [[146  82]]

 [[145  83]]

 [[145  84]]

 [[144  85]]

 [[144  87]]

 [[143  88]]

 [[143  89]]

 [[142  90]]

 [[142  91]]

 [[141  92]]

 [[141  94]]

 [[140  95]]

 [[140  96]]

 [[139  97]]

 [[139  98]]

 [[138  99]]

 [[138 100]]

 [[131 107]]

 [[130 107]]

 [[128 109]]

 [[127

[[[178   0]]

 [[178   1]]

 [[176   3]]

 [[176   4]]

 [[175   5]]

 [[175   6]]

 [[174   7]]

 [[174   8]]

 [[172  10]]

 [[172  11]]

 [[170  13]]

 [[170  14]]

 [[169  15]]

 [[169  16]]

 [[161  24]]

 [[161  25]]

 [[159  27]]

 [[159  28]]

 [[156  31]]

 [[156  32]]

 [[154  34]]

 [[154  35]]

 [[151  38]]

 [[151  39]]

 [[148  42]]

 [[148  43]]

 [[147  44]]

 [[147  45]]

 [[145  47]]

 [[145  48]]

 [[144  49]]

 [[144  55]]

 [[145  56]]

 [[145  58]]

 [[146  59]]

 [[146  61]]

 [[147  62]]

 [[147  63]]

 [[148  64]]

 [[148  65]]

 [[149  66]]

 [[149  68]]

 [[150  69]]

 [[150  75]]

 [[149  76]]

 [[149  78]]

 [[148  79]]

 [[148  80]]

 [[147  81]]

 [[147  83]]

 [[146  84]]

 [[146  85]]

 [[145  86]]

 [[145  88]]

 [[143  90]]

 [[143  92]]

 [[142  93]]

 [[142  94]]

 [[141  95]]

 [[141  96]]

 [[140  97]]

 [[140  98]]

 [[133 105]]

 [[132 105]]

 [[123 114]]

 [[123 115]]

 [[122 116]]

 [[122 117]]

 [[114 125]]

 [[113 125]]

 [[110 128]]

 [[110

[[[183   0]]

 [[181   2]]

 [[181   3]]

 [[179   5]]

 [[179   6]]

 [[178   7]]

 [[178   8]]

 [[176  10]]

 [[176  11]]

 [[174  13]]

 [[174  15]]

 [[169  20]]

 [[168  20]]

 [[165  23]]

 [[165  24]]

 [[162  27]]

 [[162  28]]

 [[158  32]]

 [[158  33]]

 [[157  34]]

 [[157  35]]

 [[152  40]]

 [[152  41]]

 [[150  43]]

 [[150  44]]

 [[149  45]]

 [[149  46]]

 [[147  48]]

 [[147  55]]

 [[148  56]]

 [[148  58]]

 [[149  59]]

 [[149  62]]

 [[150  63]]

 [[150  64]]

 [[151  65]]

 [[151  66]]

 [[152  67]]

 [[152  71]]

 [[153  72]]

 [[153  73]]

 [[152  74]]

 [[152  77]]

 [[151  78]]

 [[151  79]]

 [[150  80]]

 [[150  81]]

 [[149  82]]

 [[149  83]]

 [[148  84]]

 [[148  86]]

 [[147  87]]

 [[147  88]]

 [[146  89]]

 [[146  91]]

 [[145  92]]

 [[145  93]]

 [[144  94]]

 [[144  95]]

 [[143  96]]

 [[143  97]]

 [[141  99]]

 [[141 100]]

 [[137 104]]

 [[136 104]]

 [[134 106]]

 [[133 106]]

 [[127 112]]

 [[127 113]]

 [[124 116]]

 [[124 117]]

 [[123

In [5]:
camera.release()
cv2.destroyAllWindows

<function destroyAllWindows>

In [ ]:
#the next part of this project is saved under the python file named "handgesture_detect.py" .run it using py2.7